apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "prometheus-statsd-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    chart: {{ template "prometheus-statsd-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "prometheus-statsd-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-statsd-exporter.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end}}
    spec:
      serviceAccountName: {{ template "prometheus-statsd-exporter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          {{- range $key, $value := .Values.args }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpTargetPort }}
              protocol: TCP
            - name: statsd
              containerPort: {{ .Values.service.statsdTargetPort }}
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
     {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
