# Default values for prometheus-postgres-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/statsd-exporter
  tag: v0.7.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 80
  httpTargetPort: 9102
  statsdPort: 9125
  statsdTargetPort: 9125

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: false

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

args:
  "log.level": "info"
  "web.listen-address": ":9102"
  "web.telemetry-path": "/metrics"
  "statsd.listen-udp": ":9125"
